["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
mockEmpiricOracle = [
    "tests/mocks/empiricOracle.cairo",
]

pool = [
    "src/morphine/pool/pool.cairo",
]
