[project]
protostar-version = "0.8.1"
lib-path = "lib"                           
cairo-path = ["lib"] 

[contracts]


drip_infra_factory = ["lib/morphine/deploymentHelpers/dripInfraFactory.cairo"]
drip_manager = ["lib/morphine/borrowModules/drip/dripManager.cairo"]

drip_transit = ["lib/morphine/borrowModules/drip/dripTransit.cairo"]
drip_configurator = ["lib/morphine/borrowModules/drip/dripConfigurator.cairo"]
