[project]
protostar-version = "0.8.1"
lib-path = "lib"                           
cairo-path = ["lib"] 

[contracts]
erc20 = ["lib/openzeppelin/token/erc20/presets/ERC20Mintable.cairo"]
faucet = ["lib/utils/faucet.cairo"]


