[project]
protostar-version = "0.8.1"
lib-path = "lib"                           
cairo-path = ["lib"] 

[contracts]

drip_manager = ["lib/morphine/drip/dripManager.cairo"]
drip_transit = ["lib/morphine/drip/dripTransit.cairo"]
drip_configurator = ["lib/morphine/drip/dripConfigurator.cairo"]
drip_infra_factory = ["lib/morphine/deployment/dripInfraFactory.cairo"]