[project]
protostar-version = "0.8.1"
lib-path = "lib"                           
cairo-path = ["lib"] 

[contracts]
base_adapter = ["lib/morphine/adapters/baseAdapter.cairo"]
erc4626_adapter = ["lib/morphine/adapters/ERC4626/ERC4626.cairo"]
jediswap_adapter = ["lib/morphine/adapters/AMM/jediswap.cairo"]
